version: '3.3'

services:
  billar-postgres:
    image: postgres:14.4
    container_name: billar-postgres
    ports:
      - '5439:5439'
    expose:
      - '5439'
    restart: unless-stopped
    volumes:
      - ./databases/postgres/:/var/lib/postgresql/data
    networks:
      - nginxproxy_billar_app
    command:
      - '-p 5439'
    env_file:
      - .env.production.example

  billar-node:
    image: ghcr.io/nandawtek/billar-api:${APP_VERSION}
    container_name: billar-node
    depends_on:
      - billar-postgres
    ports:
      - '8000:8000'
      - '8001:8001'
    restart: unless-stopped
    networks:
      - nginxproxy_billar_app
    env_file:
      - .env.production.example
    command: sh -c "sleep 5; pm2-runtime start ecosystem.config.js --watch"

networks:
  nginxproxy_billar_app:
    external:
      name: nginxproxy_billar_app
