name: Build and Push Docker Image

on:
  pull_request:
    branches:
      - production
    types: [closed]

env:
  DOCKER_REGISTRY: docker.pkg.github.com
  DOCKER_IMAGE: nandawtek/billar-api

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install jq
        run: sudo apt-get install jq -y

      - name: Get Package Version
        id: get_version
        run: echo "::set-output name=version::$(cat package.json | jq -r .version)"

      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${DOCKER_REGISTRY}/${DOCKER_IMAGE}:${{ steps.get_version.outputs.version }}

      - name: Login to GitHub Package Registry
        uses: actions/docker/login@v1
        with:
          registry: docker.pkg.github.com

      - name: Push Docker Image
        uses: docker/push-action@v1
        with:
          tags: ${DOCKER_REGISTRY}/${DOCKER_IMAGE}:${{ steps.get_version.outputs.version }}
