name: Build and Push Docker Image

on:
  pull_request:
    branches:
      - production

env:
  DOCKER_IMAGE: nandawtek/billar-api
  IMAGE_NAME: billar-api

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install jq
        run: sudo apt-get install jq -y

      - name: Get Package Version
        id: get_version
        run: echo "::set-output name=version::$(cat package.json | jq -r .version)"

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ${{ inputs.dockerfile }}
          push: true
          tags: ghcr.io/nandawtek/billar-api:${{ steps.get_version.outputs.version }}
