name: Billar API

on:
  push:
    branches: [main, '*/*']
  workflow_call:

jobs:
  container-job:
    runs-on: ubuntu-latest
    container: node:16
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: secret_password
          POSTGRES_USER: user_name
          POSTGRES_DB: database_name
          POSTGRES_PORT: 5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Add .env
        run: cp .env.example .env && cat .env

      - name: Create Logs File
        run: mkdir logs && touch logs/logs.log

      - name: Launch Test
        run: yarn test
